### ISSUE TITLE
Collaborate?

### ISSUE THREAD

**Issue by jamen** [ColinEberhardt/rollup-plugin-webassembly#1]
Hello! :wave: 

I just wanted to ask, have you seen [rollup-plugin-wasm](https://github.com/jamen/rollup-plugin-wasm) and would you want to collab?

It is similar by embedding WebAssembly as base64.  It also lets you import source files (e.g., `.cc`) which compile & embed as WebAssembly.

Edit: I notice yours is async.  This is something I would like to add!  If you have ideas let me know.  :smile:

**Comment by ColinEberhardt** [comment]
Hi @jamen - I only saw your plugin when I added mine to the list! Yes, happy to collaborate.

I must admit, I did spot a few problems with your implementation, and was going to raise an issue. For wasm modules > 4k the compilation is always async, hence the need to return a promise. Also, your plugin internalises quite a bit of configuration (module imports, emscripten command line args), that developers need to be able to modify.

This is why I kept things very very simple for this plugin!

**Comment by jamen** [comment]
Great, sent an [invite!](https://github.com/jamen/rollup-plugin-wasm/invitations)  I completely agree with the concerns btw, see [this PR](https://github.com/jamen/rollup-plugin-wasm/pull/3) which attempts to address it.

P.S. We should see about [caching compiled modules using IndexedDB](https://github.com/jamen/rollup-plugin-wasm/issues/2), and the idea in #2 with using `fetch` is something I would like to experiment with too.  :smile:

**Comment by ColinEberhardt** [comment]
Cool - sounds good to me :-)

How about we reach out to Rich Harris (rollup) and look to move this plugin into the rollup organisation?

**Comment by jamen** [comment]
Sure, that would be great!  @rich-harris are you interested in transferring `rollup-plugin-wasm` to the `rollup` organization?  If so, how should we go about it?

**Comment by ColinEberhardt** [comment]
I'm not 100% sure Rich is active on Rollup any more, so have just raised an issue to see whether they'd be interested in this suggestion.

**Comment by Rich-Harris** [comment]
Sorry for the radio silence! Vacation, work, other projects, etc etc. Sure, we can transfer it to the main org, that way more people will be able to help out (in theory). Thanks!

**Comment by jamen** [comment]
Great! @Rich-Harris So how should I transfer?  Trying directly to rollup gives me permissions error.
